### ISSUE TITLE
Alternative for market history ESI endpoint

### ISSUE THREAD

**Issue by tkhamez** [bravecollective/moon-mining-manager#14]
CCP has disabled the `markets/{region_id}/history/` endpoint, which is used to update the mineral values ([test](https://esi.evetech.net/latest/markets/10000001/history/?datasource=tranquility&type_id=27942)).

That was Nov. 22, see also https://github.com/esi/esi-issues/issues/1338#issuecomment-1310205130.

We need an alternative.

**Comment by walaydenobsidia** [comment]
I already have a process that extracts data from several ESI endpoints to resolve _current_ market orders.  With, for instance, a daily pull from these endpoints, and a refresh of the data model that joins the relationships, it'd be pretty trivial to have the resulting market orders be output as a dataset in an accessible location.  I don't know anything about front-end development to know what do from there, but I could, for instance, drop a file of all current market orders, both buy and sell, into a publicly accessible json file.  Could also write the data to any number of other places in any number of formats.

**Comment by tkhamez** [comment]
I don't want to use any other API for it - the risk of it disappearing or breaking is too great.

It would need to be implemented here [UpdateMaterialValue.php](https://github.com/bravecollective/moon-mining-manager/blob/master/app/Jobs/UpdateMaterialValue.php) using ESI directly.

But, CCP just said that they will bring it back, not when though.

**Comment by tkhamez** [comment]
The endpoint is back.
