### ISSUE TITLE
Taxation on waste generation in public mining

### ISSUE THREAD

**Issue by quierati** [bravecollective/moon-mining-manager#26]
Brave does not clearly specify which modules, crystals and drones we can use for the types of resources extracted from public moons, as our neighbors do.  See: https://wiki.bravecollective.com/member/alliance/industry/moonmining

Increasingly, we are seeing several multiboxing players using T2 modules and drones with B II crystals to obtain scarce resources (such as R64, R32) and generating waste ranging from 34% to 93%.

### This situation is generating losses of billions of isk in fees for the alliance in each extraction, also affecting prices on the market and other mining players who do not generate waste using t1 modules and drones. 

The losses can be easily calculated by cross-referencing the data per ore made available at each extraction with the fees actually charged on that resource.

Currently, the software does not charge for the volumes of resources wasted due to the use of T2 modules and drones and various types of crystals when mining public moons.

To implement this, we will have to see if we can somehow collect information on the amounts of waste generated in mining through the EVE API and also review the mining policies to define the requirements for applying charges on these resources with the alliance.

**Comment by tkhamez** [comment]
ESI does not contain the amount of residue that a character generates.

**Comment by quierati** [comment]
Hi @tkhamez :)

I've checked my consumption via ESI and also via the Mining Ledger UI  and the application is *recording and charging* for all the minerals collected, including waste.

> When I opened this application it wasn't clear that the waste was included in the total mined, as we can see in the following images.

### Moon Mining Manager Log
![moon-mining-manager-brave-log](https://github.com/bravecollective/moon-mining-manager/assets/1810569/87fb2f55-8b16-4557-aa90-d486fc091cbb)



### UI Mining Ledger Logs
![Mining-Ledger-UI-Logs](https://github.com/bravecollective/moon-mining-manager/assets/1810569/6dac175f-a7c6-42e8-9d98-88b1f523c8bf)

### ESI
![esi-mining-log](https://github.com/bravecollective/moon-mining-manager/assets/1810569/c4666cde-1ac4-4240-832b-92c560b1284f)

> **The ESI is recording the total amount mined, so the application is correctly charging the fees.**
