### ISSUE TITLE
Update Laravel

### ISSUE THREAD

**Issue by tkhamez** [bravecollective/moon-mining-manager#3]
Update to the latest [Laravel](https://laravel.com/) version.

This includes making the application compatible with PHP 8.

**Comment by tkhamez** [comment]
JAMES TAL

**Comment by drkthunder02** [comment]
Sure this doesn't need to be upgraded to Laravel 8 or Laravel 9?

**Comment by tkhamez** [comment]
It should be updated to the latest LTS version.

**Comment by tkhamez** [comment]
Amaren Otsada

**Comment by tkhamez** [comment]
It looks like Laravel does not provide LTS versions any more, so it should be updated to v9 which still supports PHP 8.0.

**Comment by drkthunder02** [comment]
Still on my todo list, just been super busy with work and setting up a new server.  Will have this completed before the end of the year.  All that should need to be done is testing.

**Comment by tkhamez** [comment]
Feb 23: AzAkiR NaLDa
